/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poc_front;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;

/**
 *
 * @author jguty
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        enrollmentCompanyName = new javax.swing.JTextField();
        enrollmentCrowdsourcerName = new javax.swing.JTextField();
        enrollmentMicrotaskName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paymentCompanyName = new javax.swing.JTextField();
        paymentCrowdsourcerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paymentMicrotaskName = new javax.swing.JTextField();
        paymentDescription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        enrollmentInsertButton = new javax.swing.JButton();
        paymentInsertButton = new javax.swing.JButton();
        enrollmentSuccessMessage = new javax.swing.JLabel();
        paymentSuccessMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BlockChainDisplayer = new javax.swing.JTextArea();
        getBlockChainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enrollmentCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentCompanyNameActionPerformed(evt);
            }
        });

        enrollmentCrowdsourcerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentCrowdsourcerNameActionPerformed(evt);
            }
        });

        enrollmentMicrotaskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentMicrotaskNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la compañía afiliada");

        jLabel2.setText("Nombre del contratado");

        jLabel3.setText("Nombre de microtarea");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Ingresar contratación a microtarea");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Ingresar registro de pago");

        jLabel6.setText("Nombre de la compañía afiliada");

        paymentCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentCompanyNameActionPerformed(evt);
            }
        });

        paymentCrowdsourcerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentCrowdsourcerNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre del contratado");

        jLabel8.setText("Nombre de microtarea");

        paymentMicrotaskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMicrotaskNameActionPerformed(evt);
            }
        });

        paymentDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentDescriptionActionPerformed(evt);
            }
        });

        jLabel9.setText("Pago");

        enrollmentInsertButton.setText("Insertar");
        enrollmentInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentInsertButtonActionPerformed(evt);
            }
        });

        paymentInsertButton.setText("Insertar");
        paymentInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentInsertButtonActionPerformed(evt);
            }
        });

        enrollmentSuccessMessage.setText("            ");

        paymentSuccessMessage.setText("            ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollmentCompanyName)
                    .addComponent(enrollmentCrowdsourcerName, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(enrollmentMicrotaskName, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(paymentCompanyName)
                    .addComponent(paymentCrowdsourcerName, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(paymentMicrotaskName, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(paymentDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(enrollmentInsertButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enrollmentSuccessMessage))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(paymentInsertButton)
                                .addGap(18, 18, 18)
                                .addComponent(paymentSuccessMessage)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enrollmentCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(enrollmentCrowdsourcerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enrollmentMicrotaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollmentInsertButton)
                    .addComponent(enrollmentSuccessMessage))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(paymentCrowdsourcerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentMicrotaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentInsertButton)
                    .addComponent(paymentSuccessMessage))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar", jPanel2);

        BlockChainDisplayer.setColumns(20);
        BlockChainDisplayer.setRows(5);
        jScrollPane1.setViewportView(BlockChainDisplayer);

        getBlockChainButton.setText("Refrescar");
        getBlockChainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBlockChainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(getBlockChainButton)
                        .addContainerGap(514, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(getBlockChainButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver cadena", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollmentCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentCompanyNameActionPerformed

    private void enrollmentCrowdsourcerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentCrowdsourcerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentCrowdsourcerNameActionPerformed

    private void enrollmentMicrotaskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentMicrotaskNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentMicrotaskNameActionPerformed

    private void paymentCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentCompanyNameActionPerformed

    private void paymentCrowdsourcerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentCrowdsourcerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentCrowdsourcerNameActionPerformed

    private void paymentMicrotaskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMicrotaskNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMicrotaskNameActionPerformed

    private void paymentDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentDescriptionActionPerformed

    private void enrollmentInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentInsertButtonActionPerformed
        URL url;
        try {
            url = new URL("http://127.0.0.1:5000/insertPayment?company_name="+this.enrollmentCompanyName.getText()
                        +"&crowsourcer_name="+this.enrollmentCrowdsourcerName.getText()
                        +"&microtask_name="+this.enrollmentCrowdsourcerName.getText());
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) this.enrollmentSuccessMessage.setText("Insertado con éxito!!!");
            con.disconnect();
        } catch (Exception ex) {
            Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
            this.enrollmentSuccessMessage.setText(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_enrollmentInsertButtonActionPerformed

    private void paymentInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentInsertButtonActionPerformed
        // TODO add your handling code here:
                URL url;
        try {
            url = new URL("http://127.0.0.1:5000/insertPayment?company_name="+this.paymentCompanyName.getText()
                        +"&crowsourcer_name="+this.paymentCrowdsourcerName.getText()
                        +"&microtask_name="+this.paymentCrowdsourcerName.getText()
                        +"&payment="+this.paymentDescription.getText());
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) this.paymentSuccessMessage.setText("Insertado con éxito!!!");
            con.disconnect();
        } catch (Exception ex) {
            Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
            this.paymentSuccessMessage.setText(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_paymentInsertButtonActionPerformed

    private void getBlockChainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBlockChainButtonActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        URL url;
        try {
            url = new URL("http://127.0.0.1:5000/chain");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");
            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK){
                BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
                String inputLine;
                StringBuffer content = new StringBuffer();
                while ((inputLine = in.readLine()) != null) {
                    content.append(inputLine);
                }
                in.close();
                
                String jsonResponse = content.toString();
                JSONObject json = new JSONObject(jsonResponse);
                this.BlockChainDisplayer.setText(json.toString(4));
            }
            con.disconnect();
        } catch (Exception ex) {
            Logger.getLogger(Front.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_getBlockChainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BlockChainDisplayer;
    private javax.swing.JTextField enrollmentCompanyName;
    private javax.swing.JTextField enrollmentCrowdsourcerName;
    private javax.swing.JButton enrollmentInsertButton;
    private javax.swing.JTextField enrollmentMicrotaskName;
    private javax.swing.JLabel enrollmentSuccessMessage;
    private javax.swing.JButton getBlockChainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField paymentCompanyName;
    private javax.swing.JTextField paymentCrowdsourcerName;
    private javax.swing.JTextField paymentDescription;
    private javax.swing.JButton paymentInsertButton;
    private javax.swing.JTextField paymentMicrotaskName;
    private javax.swing.JLabel paymentSuccessMessage;
    // End of variables declaration//GEN-END:variables
}
